version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plex-wrapped-dev
    working_dir: /app
    volumes:
      # - .:/app
      # - /app/node_modules
      # - /app/.next
      - ./data:/data
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plex_wrapped?schema=public
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    container_name: plex-wrapped-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plex_wrapped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-playwright:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plex_wrapped
    ports:
      - "5433:5432"
    volumes:
      - db-data-playwright:/var/lib/postgresql/data

volumes:
  db-data:
  db-data-playwright:
